### ISSUE TITLE
This does not work on Ubuntu

### ISSUE THREAD

**Issue by yoyomonem** [akfreas/emoji-extractor-plus#3]
Hi,

I cloned this repo on an Ubuntu VM and ran `pip install -r requirements.pip`, after running `sudo apt install python-pip`, but things weren't working, not even when I ran `python3 extract.py`.

😠

**Comment by akfreas** [comment]
Thanks for checking it out! It only works for the Apple TrueType fonts, so unless you have those locally on your machine, this won't work, unfortunately :/
